name: "Build"

on:
  push:
    branches:
      - '**'
  schedule:
    # Customise: Cron interval
    - cron: "0 3,7,11,15,19,23 * * *"
  workflow_dispatch:
    inputs:
      regenerate:
        description: Enter csv of recipe slugs to specifically regenerate
        required: false
        type: string
      skip:
        description: Enter csv of recipe slugs to specifically skip
        required: false
        type: string
      verbose:
        description: Run recipe in verbose mode
        required: false
        type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.ref_name == github.event.repository.default_branch
    # Customise: Total job run time limit
    timeout-minutes: 45
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install -g sass terser html-minifier-terser

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Install calibre dependencies
        run: sudo apt-fast update -y && sudo apt-fast install --no-install-recommends -y libegl1 libopengl0

      - name: Get latest calibre version
        id: calibrelatest
        run: |
          tag="$(curl -L --retry 2 --silent --fail 'https://api.github.com/repos/kovidgoyal/calibre/releases/latest' | jq -r .tag_name)" && \
          echo "::set-output name=ver::${tag#*v}"

      - name: Calibre binaries cache
        id: cache-bin
        uses: actions/cache@v3
        with:
          path: cache/calibre
          key: cache-calibre-x86_64-${{ steps.calibrelatest.outputs.ver }}

      - name: Install calibre
        run: sh .github/workflows/install_calibre.sh

      - name: Generate periodicals
        env:
          CALIBRE_CONFIG_DIRECTORY: ${{ github.workspace }}/calibre_config/
          regenerate: ${{ github.event.inputs.regenerate }}
          skip: ${{ github.event.inputs.skip }}
          verbose: ${{ github.event.inputs.verbose }}
          accounts: ${{ secrets.accounts }}
        run: |
          export CI_PAGES_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io${GITHUB_REPOSITORY:${#GITHUB_REPOSITORY_OWNER}}/"
          sh build.sh
          if [[ -f 'job_summary.md' ]]; then cat 'job_summary.md' >> $GITHUB_STEP_SUMMARY; fi
          echo -e "\n<"'!'"-- Commit ${GITHUB_SHA:0:7} -->" >> public/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
